#!/usr/bin/env bash

for filename in *; do
    case "$filename"
    in
    README.md)
        ;;
    init.el)
        mkdir -p "$HOME/.emacs.d"
        ln -s "$HOME/dotfiles/${filename}" "$HOME/.emacs.d/"
        ;;
    install)
        ;;
    update)
        ;;
    *) ln -s "$HOME/dotfiles/${filename}" "$HOME/.${filename}"
    esac
done

cd "$HOME/dotfiles"
git submodule update --init
